# Generated by Django 5.0.7 on 2024-07-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(default=123, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="steps_to_cook",
            field=models.TextField(default=123, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(max_length=120),
        ),
    ]
