# Generated by Django 5.0.7 on 2024-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_recipe_ingredients_recipe_steps_to_cook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="steps_to_cook",
            field=models.TextField(max_length=500),
        ),
    ]
