# Generated by Django 5.0.7 on 2024-07-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_recipe_ingredients_alter_recipe_steps_to_cook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="steps_to_cook",
            field=models.TextField(max_length=600),
        ),
    ]
