# Generated by Django 5.0.7 on 2024-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(max_length=240),
        ),
    ]
