# Generated by Django 5.0.7 on 2024-08-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_alter_recipe_title_alter_review_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("non-vegetarian", "Non-Vegetarian"),
                ],
                default="vegetarian",
                max_length=20,
            ),
        ),
    ]
